---
- name: "Install systemctl-replacement version: {{ systemctl_replacement_version }}"
  get_url:
    url: "https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/{{ systemctl_replacement_version }}/files/docker/systemctl.py"
    dest: "{{ systemctl_location }}"
    force: true
    mode: 0775

- name: Create /run/systemd/system to let Ansible modules work
  file:
    path: /run/systemd/system
    state: directory
