---
- name: We only want few core services run in the container.
  systemd:
    name: "{{ item }}"
    maskes: true
  loop: "{{ systemd_masked }}"

# - command: systemctl set-default multi-user.target
