---
- block:
    - name: Systemctl prerequisites with apt
      apt:
        name: "{{ systemd_packages }}"
        state: present
        update_cache: true

    - name: Get systemd version
      command: systemctl --version
      changed_when: false
      register: systemd_version

    #FIXME: Should be working without changed_false
    - name: Add apt pin preferences
      template:
        src: apt_pinned_packages.perf.j2
        dest: "/etc/apt/preferences.d/systemd_pinned.pref"
      changed_when: false

  when: ansible_os_family == 'Debian'

- block:
    - name: Systemctl prerequisites with yum
      yum:
        name: "{{ systemd_packages }}"
        state: present
        update_cache: true

    - name: Exclude systemd from updates
      lineinfile:
        dest: /etc/yum.conf
        regexp: '^exclude='
        line: "exclude=systemd*"
        state: present

  when: ansible_distribution == 'CentOS'

- block:
    - name: Exclude systemd from updates
      lineinfile:
        dest: /etc/dnf/dnf.conf
        regexp: '^exclude='
        insertafter: '^exclude='
        line: "exclude=systemd*"
        state: present

  when: ansible_distribution == 'Fedora'
